import { describe, it, expect } from 'vitest'

const {
  mergeFeatureData,
  mergeEpics,
  writeFeatures,
  rebuildIndex
} = require('../../../server/execution/feature-store')

function makeStorage(initialFiles = {}) {
  const files = { ...initialFiles }
  return {
    readFromStorage(key) { return files[key] || null },
    writeToStorage(key, data) { files[key] = data },
    listStorageFiles(dir) {
      const prefix = dir + '/'
      return Object.keys(files)
        .filter(k => k.startsWith(prefix))
        .map(k => k.slice(prefix.length))
        .filter(k => !k.includes('/'))
    },
    _files: files
  }
}

describe('mergeFeatureData', () => {
  it('Jira-owned fields win over existing when jiraData provided', () => {
    const existing = { key: 'X-1', status: 'New', metrics: { health: 'GREEN' } }
    const jira = { key: 'X-1', status: 'In Progress', summary: 'Updated' }
    const result = mergeFeatureData(existing, null, jira)
    expect(result.status).toBe('In Progress')
    expect(result.metrics).toEqual({ health: 'GREEN' })
  })

  it('preserves existing Jira fields when jiraData is null', () => {
    const existing = { key: 'X-1', status: 'In Progress', colorStatus: 'Green' }
    const result = mergeFeatureData(existing, null, null)
    expect(result.status).toBe('In Progress')
    expect(result.colorStatus).toBe('Green')
  })

  it('pipeline-owned fields overwrite existing', () => {
    const existing = { key: 'X-1', metrics: { health: 'YELLOW' } }
    const pipeline = { key: 'X-1', metrics: { health: 'GREEN' } }
    const result = mergeFeatureData(existing, pipeline, null)
    expect(result.metrics).toEqual({ health: 'GREEN' })
  })

  it('pipeline-index-only fields are preserved across Jira syncs', () => {
    const existing = { key: 'X-1', architect: 'Bob', parentKey: 'X-0' }
    const jira = { key: 'X-1', status: 'Done' }
    const result = mergeFeatureData(existing, null, jira)
    expect(result.architect).toBe('Bob')
    expect(result.parentKey).toBe('X-0')
  })

  it('sets _sources timestamps correctly', () => {
    const result = mergeFeatureData(null, { key: 'X-1' }, { key: 'X-1' })
    expect(result._sources.pipeline).toBeDefined()
    expect(result._sources.jira).toBeDefined()
  })

  it('only sets pipeline _source when no jiraData', () => {
    const result = mergeFeatureData(null, { key: 'X-1' }, null)
    expect(result._sources.pipeline).toBeDefined()
    expect(result._sources.jira).toBeUndefined()
  })

  it('picks latest updated timestamp', () => {
    const existing = { key: 'X-1' }
    const pipeline = { key: 'X-1', updated: '2026-01-01T00:00:00Z' }
    const jira = { key: 'X-1', updated: '2026-06-01T00:00:00Z' }
    const result = mergeFeatureData(existing, pipeline, jira)
    expect(result.updated).toBe('2026-06-01T00:00:00Z')
  })

  it('Jira is source of truth for created timestamp', () => {
    const existing = { key: 'X-1', created: '2025-01-01T00:00:00Z' }
    const pipeline = { key: 'X-1', created: '2025-01-01T00:00:00Z' }
    const jira = { key: 'X-1', created: '2025-06-01T00:00:00Z' }
    const result = mergeFeatureData(existing, pipeline, jira)
    expect(result.created).toBe('2025-06-01T00:00:00Z')
  })

  it('falls back to pipeline created when Jira has none', () => {
    const pipeline = { key: 'X-1', created: '2025-03-01T00:00:00Z' }
    const result = mergeFeatureData(null, pipeline, null)
    expect(result.created).toBe('2025-03-01T00:00:00Z')
  })

  it('Jira-only discovery populates created', () => {
    const jira = { key: 'X-1', created: '2025-06-01T00:00:00Z' }
    const result = mergeFeatureData(null, null, jira)
    expect(result.created).toBe('2025-06-01T00:00:00Z')
  })

  it('handles all null inputs gracefully', () => {
    const result = mergeFeatureData(null, null, null)
    expect(result).toBeDefined()
    expect(result._sources).toEqual({})
  })

  it('writes both colorStatus and ownerStatusColor for backward compat', () => {
    const jira = { key: 'X-1', colorStatus: 'Green', ownerStatusColor: 'Green' }
    const result = mergeFeatureData(null, null, jira)
    expect(result.colorStatus).toBe('Green')
    expect(result.ownerStatusColor).toBe('Green')
  })

  // metrics generated by fetch-ep-review.py build_detail_json() @ 236e4e083a
  // (available/complete scenario), not hand-authored, to exercise the real
  // producer shape rather than an invented approximation.
  it('preserves execution/preparation fields nested under metrics (whole-object pipeline field)', () => {
    const producerMetrics = {
      totalEpics: 1, totalIssues: 2, completionPct: 100, blockerCount: 0, health: 'GREEN',
      executionIssueCount: 2, doneExecutionIssueCount: 2,
      executionState: 'complete', executionCoverage: 'available',
      executionCoverageReason: null,
      preparationReadiness: 'ready'
    }
    const pipeline = { key: 'X-1', metrics: producerMetrics }
    const result = mergeFeatureData(null, pipeline, null)
    expect(result.metrics).toEqual(producerMetrics)
  })
})

describe('mergeEpics', () => {
  // Regression: Jira's sparse { key, summary, status }-only discovery must not
  // erase the producer's issues[]/execution counts (previously overwrote them).
  const producerEpicA = {
    key: 'EP-A', summary: 'Old summary A', status: 'New', statusCategory: 'To Do',
    fixVersions: ['1.0'], executionIssueCount: 2, doneExecutionIssueCount: 0,
    issues: [{ key: 'I-1', summary: 'Do the thing', isPreparation: false }]
  }
  const producerEpicB = {
    key: 'EP-B', summary: 'Old summary B', status: 'In Progress', statusCategory: 'In Progress',
    executionIssueCount: 0, doneExecutionIssueCount: 0, issues: []
  }

  it('refreshes only summary/status per matched Epic, preserving producer-owned fields', () => {
    const jiraEpics = [{ key: 'EP-A', summary: 'New summary A', status: 'In Progress' }]
    const [merged] = mergeEpics([producerEpicA], jiraEpics)

    expect(merged.summary).toBe('New summary A')
    expect(merged.status).toBe('In Progress')
    expect(merged.fixVersions).toEqual(['1.0'])
    expect(merged.issues).toEqual(producerEpicA.issues)
    expect(merged.executionIssueCount).toBe(2)
    expect(merged.doneExecutionIssueCount).toBe(0)
  })

  it('is order-independent — matches by key regardless of array position', () => {
    const jiraEpics = [
      { key: 'EP-B', summary: 'New B', status: 'Done' },
      { key: 'EP-A', summary: 'New A', status: 'Done' }
    ]
    const merged = mergeEpics([producerEpicA, producerEpicB], jiraEpics)

    expect(merged.map(e => e.key)).toEqual(['EP-A', 'EP-B'])
    expect(merged[0].summary).toBe('New A')
    expect(merged[1].summary).toBe('New B')
  })

  it('drops a producer Epic no longer present in the Jira snapshot', () => {
    const jiraEpics = [{ key: 'EP-B', summary: 'Old summary B', status: 'In Progress' }]
    const merged = mergeEpics([producerEpicA, producerEpicB], jiraEpics)
    expect(merged.map(e => e.key)).toEqual(['EP-B'])
  })

  it('an explicit empty Jira snapshot removes all Epics', () => {
    const merged = mergeEpics([producerEpicA, producerEpicB], [])
    expect(merged).toEqual([])
  })

  it('appends an Epic Jira discovered that the producer does not know about yet', () => {
    const jiraEpics = [
      { key: 'EP-A', summary: producerEpicA.summary, status: producerEpicA.status },
      { key: 'EP-NEW', summary: 'Brand new', status: 'New' }
    ]
    const merged = mergeEpics([producerEpicA], jiraEpics)
    expect(merged).toEqual([producerEpicA, { key: 'EP-NEW', summary: 'Brand new', status: 'New' }])
  })

  it('preserves explicit null/zero/false execution values untouched, not just truthy ones', () => {
    const epic = {
      key: 'EP-C', summary: 'Old', status: 'New',
      executionIssueCount: null, doneExecutionIssueCount: null,
      issues: [{ key: 'I-2', summary: 'Prep doc', isPreparation: true }]
    }
    const [merged] = mergeEpics([epic], [{ key: 'EP-C', summary: 'Fresh', status: 'New' }])
    expect(merged.executionIssueCount).toBeNull()
    expect(merged.doneExecutionIssueCount).toBeNull()
    expect(merged.issues[0].isPreparation).toBe(true)
  })

  it('does not fabricate execution fields on an old producer payload that never had them', () => {
    const legacyEpic = { key: 'EP-D', summary: 'Old', status: 'New', issues: [{ key: 'I-3', summary: 'x' }] }
    const [merged] = mergeEpics([legacyEpic], [{ key: 'EP-D', summary: 'Fresh', status: 'Closed' }])
    expect(merged.executionIssueCount).toBeUndefined()
    expect(merged.issues[0].isPreparation).toBeUndefined()
  })
})

describe('mergeFeatureData — Epics ownership', () => {
  it('post-ingest: fresh pipeline Epics survive same-cycle Jira enrichment (gitlab-fetch.js path)', () => {
    const pipeline = {
      key: 'X-1',
      epics: [{
        key: 'EP-A', summary: 'Producer summary', status: 'New',
        executionIssueCount: 3, doneExecutionIssueCount: 1,
        issues: [{ key: 'I-1', summary: 'Implement thing', isPreparation: false }]
      }]
    }
    const jira = { key: 'X-1', status: 'In Progress', epics: [{ key: 'EP-A', summary: 'Jira summary', status: 'In Review' }] }
    const result = mergeFeatureData(null, pipeline, jira)

    expect(result.epics[0].status).toBe('In Review')
    expect(result.epics[0].executionIssueCount).toBe(3)
    expect(result.epics[0].issues).toEqual(pipeline.epics[0].issues)
  })

  it('periodic Jira-only sync preserves stored producer Epics (jira-sync.js path)', () => {
    const existing = {
      key: 'X-1',
      epics: [{
        key: 'EP-A', summary: 'Producer summary', status: 'New',
        executionIssueCount: 5, doneExecutionIssueCount: 5,
        issues: [{ key: 'I-1', summary: 'Done thing', isPreparation: false }]
      }]
    }
    const jira = { key: 'X-1', status: 'Done', epics: [{ key: 'EP-A', summary: 'Producer summary', status: 'Done' }] }
    const result = mergeFeatureData(existing, null, jira)

    expect(result.epics[0].status).toBe('Done')
    expect(result.epics[0].executionIssueCount).toBe(5)
    expect(result.epics[0].issues).toEqual(existing.epics[0].issues)
  })

  it('leaves epics untouched when jiraData carries no epics field at all', () => {
    const existing = { key: 'X-1', epics: [{ key: 'EP-A', summary: 'S', status: 'New', executionIssueCount: 1 }] }
    const result = mergeFeatureData(existing, null, { key: 'X-1', status: 'Done' })
    expect(result.epics).toEqual(existing.epics)
  })

  it('drops a stored Epic no longer in a successful Jira snapshot (unlinked)', () => {
    const existing = {
      key: 'X-1',
      epics: [
        { key: 'EP-A', summary: 'S', status: 'New', executionIssueCount: 1 },
        { key: 'EP-B', summary: 'Unlinked now', status: 'New', executionIssueCount: 0 }
      ]
    }
    const jira = { key: 'X-1', status: 'Done', epics: [{ key: 'EP-A', summary: 'S', status: 'New' }] }
    const result = mergeFeatureData(existing, null, jira)
    expect(result.epics.map(e => e.key)).toEqual(['EP-A'])
  })

  it('an explicit empty Jira snapshot removes all stored Epics', () => {
    const existing = { key: 'X-1', epics: [{ key: 'EP-A', summary: 'S', status: 'New', executionIssueCount: 1 }] }
    const jira = { key: 'X-1', status: 'Done', epics: [] }
    const result = mergeFeatureData(existing, null, jira)
    expect(result.epics).toEqual([])
  })

  it('preserves stored Epics when Jira enrichment fails for this feature entirely', () => {
    const existing = { key: 'X-1', epics: [{ key: 'EP-A', summary: 'S', status: 'New', executionIssueCount: 1 }] }
    const result = mergeFeatureData(existing, null, null)
    expect(result.epics).toEqual(existing.epics)
  })

  it('adds a newly-discovered Jira Epic sparse alongside preserved rich Epics', () => {
    const existing = {
      key: 'X-1',
      epics: [{
        key: 'EP-A', summary: 'S', status: 'New',
        executionIssueCount: 4, issues: [{ key: 'I-1', summary: 'x', isPreparation: false }]
      }]
    }
    const jira = {
      key: 'X-1',
      status: 'Done',
      epics: [
        { key: 'EP-A', summary: 'S', status: 'New' },
        { key: 'EP-NEW', summary: 'Just linked', status: 'New' }
      ]
    }
    const result = mergeFeatureData(existing, null, jira)
    expect(result.epics).toEqual([
      existing.epics[0],
      { key: 'EP-NEW', summary: 'Just linked', status: 'New' }
    ])
  })
})

describe('mergeFeatureData — execution progress invalidation on Epic membership change', () => {
  const availableMetrics = {
    totalEpics: 2, totalIssues: 6, completionPct: 50, blockerCount: 0, health: 'YELLOW',
    executionIssueCount: 6, doneExecutionIssueCount: 3,
    executionState: 'in-progress', executionCoverage: 'available',
    executionCoverageReason: null, preparationReadiness: 'ready'
  }
  const epicA = { key: 'EP-A', summary: 'A', status: 'New', executionIssueCount: 3, doneExecutionIssueCount: 1 }
  const epicB = { key: 'EP-B', summary: 'B', status: 'New', executionIssueCount: 3, doneExecutionIssueCount: 2 }

  it('invalidates when Jira adds an Epic beyond the metrics snapshot', () => {
    const existing = { key: 'X-1', metrics: availableMetrics, epics: [epicA, epicB] }
    const jira = { key: 'X-1', epics: [
      { key: 'EP-A', summary: 'A', status: 'New' },
      { key: 'EP-B', summary: 'B', status: 'New' },
      { key: 'EP-NEW', summary: 'New', status: 'New' }
    ] }
    const result = mergeFeatureData(existing, null, jira)

    expect(result.metrics.executionCoverage).toBe('insufficient-data')
    expect(result.metrics.executionCoverageReason).toBeNull()
    expect(result.metrics.executionState).toBeNull()
    expect(result.metrics.executionIssueCount).toBeNull()
    expect(result.metrics.doneExecutionIssueCount).toBeNull()
    // Legacy metrics and preparation readiness are untouched
    expect(result.metrics.totalEpics).toBe(2)
    expect(result.metrics.health).toBe('YELLOW')
    expect(result.metrics.preparationReadiness).toBe('ready')
  })

  it('invalidates when Jira removes an Epic the metrics snapshot counted', () => {
    const existing = { key: 'X-1', metrics: availableMetrics, epics: [epicA, epicB] }
    const jira = { key: 'X-1', epics: [{ key: 'EP-A', summary: 'A', status: 'New' }] }
    const result = mergeFeatureData(existing, null, jira)

    expect(result.metrics.executionCoverage).toBe('insufficient-data')
    expect(result.metrics.executionIssueCount).toBeNull()
  })

  it('does not invalidate when Epic membership is unchanged, only reordered', () => {
    const existing = { key: 'X-1', metrics: availableMetrics, epics: [epicA, epicB] }
    const jira = { key: 'X-1', epics: [
      { key: 'EP-B', summary: 'B', status: 'New' },
      { key: 'EP-A', summary: 'A', status: 'New' }
    ] }
    const result = mergeFeatureData(existing, null, jira)

    expect(result.metrics).toEqual(availableMetrics)
  })

  it('does not invalidate on a summary/status-only refresh of the same Epics', () => {
    const existing = { key: 'X-1', metrics: availableMetrics, epics: [epicA, epicB] }
    const jira = { key: 'X-1', epics: [
      { key: 'EP-A', summary: 'Refreshed A', status: 'In Progress' },
      { key: 'EP-B', summary: 'B', status: 'New' }
    ] }
    const result = mergeFeatureData(existing, null, jira)

    expect(result.metrics).toEqual(availableMetrics)
    expect(result.epics[0].summary).toBe('Refreshed A')
  })

  it('does not invalidate when Jira discovery fails or is skipped entirely', () => {
    const existing = { key: 'X-1', metrics: availableMetrics, epics: [epicA] }
    const result = mergeFeatureData(existing, null, null)

    expect(result.metrics).toEqual(availableMetrics)
    expect(result.epics).toEqual([epicA])
  })

  it('invalidation persists through a subsequent Jira-only refresh with unchanged membership', () => {
    const existing = { key: 'X-1', metrics: availableMetrics, epics: [epicA, epicB] }
    const afterMembershipChange = mergeFeatureData(
      existing, null, { key: 'X-1', epics: [{ key: 'EP-A', summary: 'A', status: 'New' }] }
    )
    expect(afterMembershipChange.metrics.executionCoverage).toBe('insufficient-data')

    const afterFollowUpSync = mergeFeatureData(
      afterMembershipChange, null, { key: 'X-1', epics: [{ key: 'EP-A', summary: 'A', status: 'New' }] }
    )
    expect(afterFollowUpSync.metrics.executionCoverage).toBe('insufficient-data')
    expect(afterFollowUpSync.metrics.executionIssueCount).toBeNull()
  })

  it('a compatible fresh producer snapshot restores available progress', () => {
    const invalidated = {
      key: 'X-1',
      metrics: { ...availableMetrics, executionCoverage: 'insufficient-data', executionCoverageReason: null, executionState: null, executionIssueCount: null, doneExecutionIssueCount: null },
      epics: [epicA]
    }
    const freshMetrics = { ...availableMetrics, totalEpics: 1, executionIssueCount: 3, doneExecutionIssueCount: 1, executionState: 'in-progress' }
    const pipeline = { key: 'X-1', metrics: freshMetrics, epics: [epicA] }
    const jira = { key: 'X-1', epics: [{ key: 'EP-A', summary: 'A', status: 'New' }] }
    const result = mergeFeatureData(invalidated, pipeline, jira)

    expect(result.metrics).toEqual(freshMetrics)
  })

  it('does not mutate the existing metrics object when invalidating', () => {
    const metricsCopy = { ...availableMetrics }
    const existing = { key: 'X-1', metrics: metricsCopy, epics: [epicA, epicB] }
    mergeFeatureData(existing, null, { key: 'X-1', epics: [{ key: 'EP-A', summary: 'A', status: 'New' }] })

    expect(metricsCopy).toEqual(availableMetrics)
  })
})

describe('rebuildIndex', () => {
  it('builds index from feature files', async () => {
    const storage = makeStorage({
      'releases/execution/features/X-1.json': {
        key: 'X-1', summary: 'Feature 1', status: 'New',
        statusCategory: 'To Do', priority: 'Normal',
        assignee: { displayName: 'Alice', accountId: 'a-1' },
        fixVersions: ['3.5'], labels: ['core'],
        metrics: { completionPct: 50, totalEpics: 2, totalIssues: 10, blockerCount: 1, health: 'YELLOW' },
        updated: '2026-01-01', colorStatus: 'Green'
      },
      'releases/execution/features/X-2.json': {
        key: 'X-2', summary: 'Feature 2', status: 'Done',
        assignee: 'Bob',
        metrics: null
      }
    })

    await rebuildIndex(storage)

    const index = storage._files['releases/execution/index.json']
    expect(index.featureCount).toBe(2)
    expect(index.features[0].assignee).toBe('Alice') // object -> string for index
    expect(index.features[0].completionPct).toBe(50)
    expect(index.features[0].health).toBe('YELLOW')
    expect(index.features[0].colorStatus).toBe('Green')
    expect(index.features[0].ownerStatusColor).toBe('Green')
    expect(index.features[1].assignee).toBe('Bob') // already string
  })

  it('writes empty index when no feature files exist', async () => {
    const storage = makeStorage({})
    await rebuildIndex(storage)

    const index = storage._files['releases/execution/index.json']
    expect(index.featureCount).toBe(0)
    expect(index.features).toEqual([])
  })

  // metrics below are copies of fetch-ep-review.py build_detail_json() output
  // @ 236e4e083a for each distinct coverage case (§6.2), not hand-authored.
  it('passes through execution/preparation fields, preserving null vs zero', async () => {
    const storage = makeStorage({
      // available/complete: nonzero counts, all Done
      'releases/execution/features/X-1.json': {
        key: 'X-1', summary: 'Available complete', status: 'In Progress',
        metrics: {
          totalEpics: 1, totalIssues: 2, completionPct: 100, blockerCount: 0, health: 'GREEN',
          executionIssueCount: 2, doneExecutionIssueCount: 2,
          executionState: 'complete', executionCoverage: 'available',
          executionCoverageReason: null,
          preparationReadiness: 'ready'
        }
      },
      // insufficient-data: epics exist but zero observed child issues -> null, not zero
      'releases/execution/features/X-2.json': {
        key: 'X-2', summary: 'Insufficient data', status: 'In Progress',
        metrics: {
          totalEpics: 1, totalIssues: 0, completionPct: 0, blockerCount: 0, health: 'YELLOW',
          executionIssueCount: null, doneExecutionIssueCount: null,
          executionState: null, executionCoverage: 'insufficient-data',
          executionCoverageReason: 'epics-without-issue-detail',
          preparationReadiness: 'not-applicable'
        }
      },
      // empty: no epics, no issues -> measured zero, not null
      'releases/execution/features/X-3.json': {
        key: 'X-3', summary: 'Empty scope', status: 'In Progress',
        metrics: {
          totalEpics: 0, totalIssues: 0, completionPct: 0, blockerCount: 0, health: 'YELLOW',
          executionIssueCount: 0, doneExecutionIssueCount: 0,
          executionState: 'no-tracked-work', executionCoverage: 'empty',
          executionCoverageReason: 'no-epics',
          preparationReadiness: 'not-applicable'
        }
      }
    })

    await rebuildIndex(storage)
    const byKey = Object.fromEntries(
      storage._files['releases/execution/index.json'].features.map(f => [f.key, f])
    )

    expect(byKey['X-1'].executionIssueCount).toBe(2)
    expect(byKey['X-1'].doneExecutionIssueCount).toBe(2)
    expect(byKey['X-1'].executionState).toBe('complete')
    expect(byKey['X-1'].executionCoverage).toBe('available')
    expect(byKey['X-1'].executionCoverageReason).toBeNull()
    expect(byKey['X-1'].preparationReadiness).toBe('ready')

    expect(byKey['X-2'].executionIssueCount).toBeNull()
    expect(byKey['X-2'].doneExecutionIssueCount).toBeNull()
    expect(byKey['X-2'].executionState).toBeNull()
    expect(byKey['X-2'].executionCoverage).toBe('insufficient-data')
    expect(byKey['X-2'].executionCoverageReason).toBe('epics-without-issue-detail')
    expect(byKey['X-2'].preparationReadiness).toBe('not-applicable')

    expect(byKey['X-3'].executionIssueCount).toBe(0)
    expect(byKey['X-3'].doneExecutionIssueCount).toBe(0)
    expect(byKey['X-3'].executionState).toBe('no-tracked-work')
    expect(byKey['X-3'].executionCoverage).toBe('empty')
    expect(byKey['X-3'].executionCoverageReason).toBe('no-epics')
  })

  // metrics generated by fetch-ep-review.py compute_metrics()/enrich_epics_with_provenance()
  // @ 077f7326da (preparation-only and hybrid epics-without-issue-detail scenarios), not
  // hand-authored, to exercise the real producer shape for the newly added reason field.
  it('passes through executionCoverageReason for preparation-only and hybrid insufficient-data', async () => {
    const storage = makeStorage({
      'releases/execution/features/X-4.json': {
        key: 'X-4', summary: 'Preparation only', status: 'In Progress',
        metrics: {
          totalEpics: 1, totalIssues: 3, completionPct: 67, blockerCount: 0, health: 'YELLOW',
          executionIssueCount: 0, doneExecutionIssueCount: 0,
          executionState: 'no-tracked-work', executionCoverage: 'empty',
          executionCoverageReason: 'preparation-only',
          preparationReadiness: 'not-applicable'
        }
      },
      // One epic's issues collected and all preparation, another epic has zero
      // collected issues at all -- the hybrid case that must NOT read as empty.
      'releases/execution/features/X-5.json': {
        key: 'X-5', summary: 'Hybrid unobserved epic', status: 'In Progress',
        metrics: {
          totalEpics: 3, totalIssues: 4, completionPct: 50, blockerCount: 0, health: 'YELLOW',
          executionIssueCount: null, doneExecutionIssueCount: null,
          executionState: null, executionCoverage: 'insufficient-data',
          executionCoverageReason: 'epics-without-issue-detail',
          preparationReadiness: 'not-applicable'
        }
      }
    })

    await rebuildIndex(storage)
    const byKey = Object.fromEntries(
      storage._files['releases/execution/index.json'].features.map(f => [f.key, f])
    )

    expect(byKey['X-4'].executionCoverage).toBe('empty')
    expect(byKey['X-4'].executionCoverageReason).toBe('preparation-only')

    expect(byKey['X-5'].executionCoverage).toBe('insufficient-data')
    expect(byKey['X-5'].executionState).toBeNull()
    expect(byKey['X-5'].executionCoverageReason).toBe('epics-without-issue-detail')
  })

  it('defaults execution/preparation fields to unavailable for an old/missing payload', async () => {
    const storage = makeStorage({
      'releases/execution/features/X-1.json': {
        key: 'X-1', summary: 'Pre-migration feature', status: 'New',
        // Legacy metrics shape predating the execution/preparation contract —
        // none of the 6 new keys exist yet.
        metrics: { completionPct: 50, totalEpics: 2, totalIssues: 10, blockerCount: 1, health: 'YELLOW' }
      },
      'releases/execution/features/X-2.json': {
        key: 'X-2', summary: 'No metrics at all', status: 'New', metrics: null
      }
    })

    await rebuildIndex(storage)
    const byKey = Object.fromEntries(
      storage._files['releases/execution/index.json'].features.map(f => [f.key, f])
    )

    for (const key of ['X-1', 'X-2']) {
      expect(byKey[key].executionIssueCount).toBeNull()
      expect(byKey[key].doneExecutionIssueCount).toBeNull()
      expect(byKey[key].executionState).toBeNull()
      expect(byKey[key].executionCoverage).toBe('insufficient-data')
      expect(byKey[key].executionCoverageReason).toBeNull()
      expect(byKey[key].preparationReadiness).toBe('unknown')
    }
  })
})

describe('writeFeatures', () => {
  it('writes feature files and rebuilds index', async () => {
    const storage = makeStorage({})
    await writeFeatures(storage, [
      { key: 'X-1', summary: 'F1', status: 'New' },
      { key: 'X-2', summary: 'F2', status: 'Done' }
    ])

    expect(storage._files['releases/execution/features/X-1.json']).toBeDefined()
    expect(storage._files['releases/execution/features/X-2.json']).toBeDefined()
    expect(storage._files['releases/execution/index.json'].featureCount).toBe(2)
  })

  it('skips features without key', async () => {
    const storage = makeStorage({})
    await writeFeatures(storage, [
      { summary: 'No key' },
      { key: 'X-1', summary: 'Has key' }
    ])

    expect(storage._files['releases/execution/features/X-1.json']).toBeDefined()
    expect(storage._files['releases/execution/index.json'].featureCount).toBe(1)
  })
})
